Repository sena-proyectos/practicas-ctm, pull requests merged in 2023-08, with the labels that each got.

#7 Estudiantes
  client/src/api/httpRequest.jsx
  client/src/components/Student/Student.jsx
  server/src/controllers/students.controllers.ts
Labels: enhancement

#10 Acta No. 5
  docs/Actas/Acta No. 5 - 03 Agosto.pdf
Labels: documentation

#11 fix: accents in table inscripciones
  server/src/db/db.sql
Labels: bug

#12 Classes API added | v3.7.0 (Server)
  server/package.json
  server/src/controllers/classes.controllers.ts
  server/src/middlewares/classes.middlewares.ts
  server/src/routes/classes.routes.ts
  server/tsconfig.json
Labels: documentation, enhancement

#14 Class detail route
  server/package.json
  server/src/controllers/classes.controllers.ts
  server/src/routes/classes.routes.ts
Labels: enhancement

#18 Class date route
  server/package.json
  server/src/controllers/classes.controllers.ts
  server/src/middlewares/classes.middlewares.ts
  server/src/routes/classes.routes.ts
  server/src/schemas/classes.schemas.ts
Labels: enhancement

#20 fix: create class and edit class routes
  server/package.json
  server/src/controllers/classes.controllers.ts
  server/src/interfaces/classes.interfaces.ts
  server/src/middlewares/classes.middlewares.ts
  server/src/schemas/classes.schemas.ts
Labels: enhancement

#21 Inscriptions count approves
  client/package.json
  client/src/components/Courses/Courses.jsx
  client/src/components/Register-list/RegisterList.jsx
  server/package.json
  server/src/controllers/inscriptions.controllers.ts
  server/src/controllers/practicalStages.controllers.ts
  server/src/middlewares/practicalStages.middlewares.ts
Labels: enhancement

#26 feat & fix: web icon added, setTimeout erased, new database and fix accents
  client/index.html
  client/src/components/Courses/Courses.jsx
  client/src/components/Student/Student.jsx
  client/src/components/Teachers/Teachers.jsx
  server/package.json
  server/src/controllers/inscriptions.controllers.ts
  server/src/controllers/practicalStages.controllers.ts
  server/src/db/db.sql
  server/src/interfaces/inscriptions.interfaces.ts
  server/src/middlewares/inscriptions.middlewares.ts
  server/src/middlewares/practicalStages.middlewares.ts
  server/src/schemas/inscriptions.schemas.ts
Labels: bug, enhancement

#28 Read excel file (client) | v0.12.0
  client/.eslintrc.json
  client/.prettierrc
  client/index.html
  client/package.json
  client/postcss.config.js
  client/src/App.jsx
  client/src/api/httpRequest.jsx
  client/src/components/Assign-class/AssignClass.jsx
  client/src/components/Bitacoras/Bitacoras.jsx
  client/src/components/Courses/Courses.jsx
  client/src/components/Footer/Footer.jsx
  client/src/components/Form/Form.jsx
  client/src/components/Home/Home.jsx
  client/src/components/Register-detail/RegisterDetails.jsx
  client/src/components/Register-list/RegisterList.jsx
  client/src/components/Register-student/RegisterStudent.jsx
  client/src/components/Search/Search.jsx
  client/src/components/Settings/Settings.jsx
  client/src/components/Siderbar/Sidebar.jsx
  client/src/components/Student-monitoring/StudentMonitoring.jsx
  client/src/components/Students/Students.jsx
  client/src/components/Teachers/Teachers.jsx
  client/src/components/User/User.jsx
  client/src/components/Utils/Card/Card.jsx
  client/src/components/Utils/Modals/Modals.jsx
  client/src/components/Utils/Pagination/Pagination.jsx
  client/src/components/Utils/Select/Select.jsx
  client/src/components/Visits/Visits.jsx
  client/src/import/staticData.jsx
  client/src/index.css
  client/src/main.jsx
  client/src/mapeo/Map.jsx
  client/src/readExcelFile/reactExcelFile.jsx
  client/src/validation/RegularExpressions.js
  client/src/validation/inscriptionsValidation.js
  client/tailwind.config.js
  client/vite.config.js
  server/src/middlewares/practicalStages.middlewares.ts
  server/tsconfig.json
Labels: enhancement

#30 Read excel file
  client/package.json
  client/src/App.jsx
  client/src/api/httpRequest.jsx
  client/src/components/Form/Form.jsx
  client/src/components/Register-list/RegisterList.jsx
  client/src/components/Utils/Button/Button.jsx
  server/package.json
  server/src/controllers/inscriptions.controllers.ts
  server/src/controllers/practicalStages.controllers.ts
  server/src/middlewares/inscriptions.middlewares.ts
  server/src/middlewares/practicalStages.middlewares.ts
  server/src/routes/inscriptions.routes.ts
Labels: enhancement

#31 Loren rama
  client/package.json
  client/src/api/httpRequest.jsx
  client/src/components/Assign-class/AssignClass.jsx
  client/src/components/Courses/Courses.jsx
  client/src/components/Register-detail/RegisterDetails.jsx
  client/src/components/Register-student/RegisterStudent.jsx
  client/src/components/Students/Students.jsx
  client/src/components/Utils/Card/Card.jsx
  client/src/components/Utils/Select/Select.jsx
  client/src/import/staticData.jsx
  server/.eslintrc.json
  server/package.json
  server/src/controllers/classes.controllers.ts
  server/src/controllers/practicalStages.controllers.ts
  server/src/controllers/students.controllers.ts
  server/src/middlewares/classes.middlewares.ts
  server/src/middlewares/practicalStages.middlewares.ts
  server/src/schemas/classes.schemas.ts
Labels: enhancement

#34 Filter course students list
  client/package.json
  client/src/App.css
  client/src/api/httpRequest.jsx
  client/src/components/Courses/Courses.jsx
  client/src/components/Register-student/RegisterStudent.jsx
  client/src/components/Search/Search.jsx
  client/src/components/Settings/Settings.jsx
  client/src/components/Student-monitoring/StudentMonitoring.jsx
  client/src/components/Students/Students.jsx
  client/src/components/User/User.jsx
  client/src/components/Utils/Modals/Modals.jsx
  client/src/readExcelFile/reactExcelFile.jsx
  server/.eslintrc.json
  server/package.json
  server/src/controllers/classes.controllers.ts
  server/src/controllers/inscriptions.controllers.ts
  server/src/controllers/practicalStages.controllers.ts
  server/src/controllers/students.controllers.ts
  server/src/middlewares/inscriptions.middlewares.ts
  server/src/middlewares/practicalStages.middlewares.ts
  server/src/routes/classes.routes.ts
  server/tsconfig.json
Labels: enhancement

#35 style: if there's no registers, say it
  client/package.json
  client/src/components/Register-list/RegisterList.jsx
Labels: bug

#36 v2.0.0-Alpha
  client/index.html
  client/package-lock.json
  client/package.json
  client/src/components/Assign-class/AssignClass.jsx
  client/src/components/Bitacoras/Bitacoras.jsx
  client/src/components/Courses/Courses.jsx
  client/src/components/Form/Form.jsx
  client/src/components/Register-detail/Approves/Docs.jsx
  client/src/components/Register-detail/RegisterDetails.jsx
  client/src/components/Register-list/RegisterList.jsx
  client/src/components/Register-student/RegisterStudent.jsx
  client/src/components/Search/Search.jsx
  client/src/components/Utils/Button/Button.jsx
  client/src/components/Utils/Modals/Modals.jsx
  client/src/index.css
  client/src/main.jsx
  client/vite.config.js
Labels: enhancement, help wanted
